import type { Document } from "../../../../types/Document";

import type { DataTableColumn } from "../../../../ui/DataTable";

import Badge from "../../../../ui/Badge";
import Button from "../../../../ui/Button";

interface DocumentColumnsProps {
  onView: (document: Document) => void;

  onDownload: (document: Document) => void;

  onArchive: (document: Document) => void;

  onDelete: (document: Document) => void;
}

function getStatusVariant(status: Document["status"]) {
  switch (status) {
    case "Generated":
      return "success";

    case "Uploaded":
      return "info";

    case "Sent":
      return "warning";

    case "Downloaded":
      return "secondary";

    case "Archived":
      return "danger";

    case "Draft":
    default:
      return "secondary";
  }
}

export function getDocumentColumns({
  onView,
  onDownload,
  onArchive,
  onDelete,
}: DocumentColumnsProps): DataTableColumn<Document>[] {
  return [
    {
      key: "documentId",
      title: "Document No.",
      sortable: true,
    },

    {
      key: "title",
      title: "Title",
      sortable: true,
      render: (_, row) => (
        <div>
          <div className="font-medium text-slate-800">
            {row.title}
          </div>

          <div className="text-xs text-slate-500">
            {row.referenceId}
          </div>
        </div>
      ),
    },

    {
      key: "module",
      title: "Module",
      sortable: true,
    },

    {
      key: "documentType",
      title: "Type",
      sortable: true,
    },

    {
      key: "version",
      title: "Version",
      align: "center",
      sortable: true,
      render: (value) => `v${value}`,
    },

    {
      key: "status",
      title: "Status",
      align: "center",
      sortable: true,
      render: (value) => (
        <Badge
          variant={getStatusVariant(
            value as Document["status"]
          )}
        >
          {String(value)}
        </Badge>
      ),
    },

    {
      key: "generatedBy",
      title: "Generated By",
      sortable: true,
    },

    {
      key: "createdAt",
      title: "Created",
      sortable: true,
      render: (value) => {
        if (!value) {
          return "-";
        }

        const date =
          (value as any)?.toDate?.() ?? value;

        return new Date(date).toLocaleDateString(
          "en-IN"
        );
      },
    },

    {
      key: "actions",
      title: "Actions",
      align: "right",

      render: (_, row) => (
        <div className="flex justify-end gap-2">

          <Button
            onClick={() => onView(row)}
          >
            View
          </Button>

          <Button
            onClick={() => onDownload(row)}
          >
            Download
          </Button>

          {!row.archived && (
            <Button
              className="bg-amber-600 hover:bg-amber-700"
              onClick={() => onArchive(row)}
            >
              Archive
            </Button>
          )}

          <Button
            className="bg-red-600 hover:bg-red-700"
            onClick={() => onDelete(row)}
          >
            Delete
          </Button>

        </div>
      ),
    },
  ];
}