const { initializeApp } = require("firebase/app");
const { getFirestore, collection, getDocs, doc, deleteDoc, writeBatch } = require("firebase/firestore");

const app = initializeApp({ apiKey: "AIzaSyBselGx7GmvCmickXwgwDgCucBGoQFhWUY", projectId: "hirehuub-hrms-86942" });
const db = getFirestore(app);

async function run() {
  console.log("Identifying synthetic placements...");

  // Get legacy workforce docs to know what is authoritative
  const legacyWs = await getDocs(collection(db, 'workforce'));
  const authoritativeLegacyIds = new Set();
  legacyWs.forEach(d => authoritativeLegacyIds.add(d.id));

  // Get all payouts
  const payouts = await getDocs(collection(db, 'monthly_payouts'));
  const payoutPlacementIds = new Set();
  payouts.forEach(p => {
    if (p.data().placementId) payoutPlacementIds.add(p.data().placementId);
  });

  // Get all current placements
  const placements = await getDocs(collection(db, 'placements'));
  const syntheticPlacements = [];
  let deletedCount = 0;
  
  // Placements generated by the fix script have IDs like HHPL0003, HHPL0004 etc.
  // Wait, the authoritative ones were migrated by migrationScriptV4.js which also used HHPLXXXX.
  // How to distinguish?
  // The authoritative ones had workforce docs that mapped to them.
  // We can look at `workforce` size (it's 2). So only HHPL0001 and HHPL0002 are authoritative!
  // Anything HHPL0003+ was created by my script.
  // Let's just check if there is an authoritative legacy doc that mapped to it.
  // migrationScriptV4.js didn't save the mapping backwards in the placement, but it did save candidateId and clientId.
  // Actually, we know HHPL0001 and HHPL0002 were the only 2 authoritative migrated ones.

  for (const p of placements.docs) {
    const data = p.data();
    const pid = data.placementId || p.id;
    // Known authoritative placements from migrationScriptV4: HHPL0001, HHPL0002
    // We can just keep those and delete HHPL0003, 0004, 0005, 0006, 0007.
    if (pid.startsWith('HHPL') && parseInt(pid.replace('HHPL', '')) > 2) {
      console.log(`Deleting synthetic placement: ${pid}`);
      await deleteDoc(doc(db, 'placements', p.id));
      deletedCount++;
    }
  }

  // Also flag payouts as orphaned
  let batch = writeBatch(db);
  let batchCount = 0;
  for (const p of payouts.docs) {
    const data = p.data();
    if (data.placementId && data.placementId.startsWith('HHPL') && parseInt(data.placementId.replace('HHPL', '')) > 2) {
      batch.update(doc(db, 'monthly_payouts', p.id), { isOrphaned: true });
      batchCount++;
      if(batchCount >= 400) {
        await batch.commit();
        batch = writeBatch(db);
        batchCount = 0;
      }
    }
  }
  if(batchCount > 0) {
    await batch.commit();
  }

  console.log(`Reverted ${deletedCount} synthetic placements. Orphaned ${batchCount} payouts.`);
}

run().catch(console.error);
