export default function CompanyFooter() {
  return (
    <footer className="mt-10 flex flex-col gap-2 border-t border-slate-300 pt-4 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between print:mt-8 print:pt-3 print:text-[10px]">
      <p>© Hire Huub People Solution Private Limited</p>
      <p className="text-left sm:text-right">
        Confidential Document · Generated by HireHuub ERP
      </p>
    </footer>
  );
}
