import { useEffect, useState } from "react";

import Card from "../../ui/Card";
import Badge from "../../ui/Badge";

import type { Document } from "../../types/Document";

import { getDocuments } from "../../services/document/documentService";

export default function DocumentHistory() {
  const [loading, setLoading] = useState(true);

  const [documents, setDocuments] = useState<Document[]>([]);

  useEffect(() => {
    loadHistory();
  }, []);

  async function loadHistory() {
    try {
      setLoading(true);

      const data = await getDocuments();

      setDocuments(data);
    } catch {
      setDocuments([]);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">

      {/* Header */}

      <div>
        <h1 className="text-3xl font-bold text-slate-800">
          Document History
        </h1>

        <p className="mt-2 text-slate-500">
          Complete audit trail of every document generated in HireHuub ERP.
        </p>
      </div>

      {/* Timeline */}

      <Card>

        {loading ? (
          <div className="py-16 text-center text-slate-500">
            Loading document history...
          </div>
        ) : documents.length === 0 ? (
          <div className="py-16 text-center text-slate-500">
            No document history available.
          </div>
        ) : (
          <div className="space-y-5">

            {documents.map((document) => (
              <div
                key={document.id}
                className="relative border-l-4 border-blue-500 pl-6 pb-8"
              >
                <div className="absolute -left-[10px] top-1 h-4 w-4 rounded-full bg-blue-500" />

                <div className="flex items-center justify-between">

                  <div>

                    <h3 className="font-semibold text-slate-800">
                      {document.title}
                    </h3>

                    <p className="text-sm text-slate-500 mt-1">
                      {document.documentId}
                    </p>

                  </div>

                  <Badge variant="secondary">
                    v{document.version}
                  </Badge>

                </div>

                <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">

                  <InfoField
                    label="Module"
                    value={document.module}
                  />

                  <InfoField
                    label="Type"
                    value={document.documentType}
                  />

                  <InfoField
                    label="Status"
                    value={document.status}
                  />

                  <InfoField
                    label="Reference"
                    value={document.referenceId}
                  />

                </div>

                <div className="mt-4 text-sm text-slate-500">

                  Generated By{" "}
                  <span className="font-medium text-slate-700">
                    {document.generatedBy}
                  </span>

                  {" • "}

                  {formatDate(document.createdAt)}

                </div>

              </div>
            ))}

          </div>
        )}

      </Card>

    </div>
  );
}

interface InfoFieldProps {
  label: string;
  value: string | number;
}

function InfoField({
  label,
  value,
}: InfoFieldProps) {
  return (
    <div>

      <p className="text-xs uppercase tracking-wide text-slate-500">
        {label}
      </p>

      <p className="mt-1 font-medium text-slate-800">
        {value}
      </p>

    </div>
  );
}

function formatDate(value: unknown) {
  if (!value) {
    return "-";
  }

  try {
    const valObj = value as { toDate?: () => Date };
    const date = typeof valObj?.toDate === 'function' ? valObj.toDate() : value;
    return new Date(date as string | number | Date).toLocaleString("en-IN");
  } catch {
    return "-";
  }
}